### ISSUE TITLE
sshpass

### ISSUE THREAD

**Issue by kingdonb** [carlosedp/openshift-on-footloose#1]
The README specifies a few brew packages to install, including sshpass

Today when I tried this, I got the following message from brew:
```
Error: No available formula with the name "sshpass"
We won't add sshpass because it makes it too easy for novice SSH users to
ruin SSH's security.
```

I went looking through the repo for any other mention of sshpass, or why you would need it, and didn't find any.  After following the tutorial steps, it's still not super clear if there's a reason why it is needed, although I got hung up with an error related to my VPN before I could get all the way into it.

I found this gist, which covers how to coerce brew into installing sshpass, maybe it will help someone:

https://gist.github.com/arunoda/7790979

Given the scary warnings from homebrew though, if there is a reason for sshpass, then perhaps a better solution can be proposed that doesn't invoke scary warnings or ruin security.

**Comment by carlosedp** [comment]
I remember sshpass was a requirement by Ansible on brew to connect to the hosts. I might try it again without sshpass just to make sure and remove the requirement.

**Comment by carlosedp** [comment]
Tested it again and it's required by Ansible to use password for SSH connections:

```
ansible-playground/linuxbox-prepare on  master at ☸️  keycloak/api-crc-testing:6443/kube:admin (keycloak)
➜ ansible -m ping all
192.168.15.15 | FAILED! => {
    "msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"
}

ansible-playground/linuxbox-prepare on  master at ☸️  keycloak/api-crc-testing:6443/kube:admin (keycloak)
➜ brew install sshpass
==> Installing sshpass from hudochenkov/sshpass
==> Downloading https://downloads.sourceforge.net/project/sshpass/sshpass/1.06/sshpass-1.06.tar.gz
Already downloaded: /Users/cdepaula/Library/Caches/Homebrew/downloads/5c6e67e910f5c482f4dffc9cd084c03424093cace4bb59904f90fdb51f57d155--sshpass-1.06.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/sshpass/1.06
==> make install
🍺  /usr/local/Cellar/sshpass/1.06: 9 files, 41.7KB, built in 9 seconds

ansible-playground/linuxbox-prepare on  master at ☸️  keycloak/api-crc-testing:6443/kube:admin (keycloak)
➜ ansible -m ping all
192.168.15.15 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

I will update the documentation since sshpass come from `hudochenkov/sshpass` homebrew tap.
